### ISSUE TITLE
导出MP4 路径错误

### ISSUE THREAD

**Issue by Djooxx** [youwen21/flybird-downloader#1]
报错:
```
open C:\Users\qwerd\m3u8Data/C:\Users\qwerd\m3u8Data\a5563f0221680d3c5eede72fead9b496/9a187bef-9cdb-4708-baa4-b8fb6408f32f/1080p/video.m3u8: The filename, directory name, or volume label syntax is incorrect.
```

**Comment by youwen21** [comment]
> 报错:
> 
> ```
> open C:\Users\qwerd\m3u8Data/C:\Users\qwerd\m3u8Data\a5563f0221680d3c5eede72fead9b496/9a187bef-9cdb-4708-baa4-b8fb6408f32f/1080p/video.m3u8: The filename, directory name, or volume label syntax is incorrect.
> ```

你使用哪个版本， 如果不是 v2.0.0,  建议升级版本。

查看版本方法：
菜单 -> help -> 关于飞鸟。

**Comment by Djooxx** [comment]
> > 报错:
> 
> > 
> 
> > ```
> 
> > open C:\Users\qwerd\m3u8Data/C:\Users\qwerd\m3u8Data\a5563f0221680d3c5eede72fead9b496/9a187bef-9cdb-4708-baa4-b8fb6408f32f/1080p/video.m3u8: The filename, directory name, or volume label syntax is incorrect.
> 
> > ```
> 
> 
> 
> 你使用哪个版本， 如果不是 v2.0.0,  建议升级版本。
> 
> 
> 
> 查看版本方法：
> 
> 菜单 -> help -> 关于飞鸟。
> 
> 

2.0

**Comment by youwen21** [comment]
> 2.0

1， 先重命名 m3u8Data目录
2， 使用 v2.0.0 重新下载视频
经过上面两个步骤 还是没解决问题的话， 加 QQ 群，在群里发我.m3u8Data数据的压缩包， 再看有什么问题。
