### ISSUE TITLE
submit err:AxiosError: Request failed with status code 500

### ISSUE THREAD

**Issue by cy920820** [youwen21/flybird-downloader#3]

**Comment by youwen21** [comment]
描述具体场景，具体问题

**Comment by cy920820** [comment]
mac 端任何有效的 m3u8 链接，点击下载都会弹出这样的提示

**Comment by cy920820** [comment]
今天早上又发现了一个问题，就是点击 IPTV 管理按钮，页面直接白屏了

![image](https://github.com/youwen21/flybird-m3u8downloader/assets/21211512/3117a592-9eec-42cd-85c2-559e0fd79879)

**Comment by youwen21** [comment]
> [cy920820](/cy920820)

链接地址发一下，  我试试。

**Comment by youwen21** [comment]
> mac 端任何有效的 m3u8 链接，点击下载都会弹出这样的提示

不确定哪些地址需要 VPN 才能访问的情况下，  使用 导入内容 功能。

**Comment by cy920820** [comment]
> > [cy920820](/cy920820)
> 
> 链接地址发一下， 我试试。

https://upyun.luckly-mjw.cn/Assets/media-source/example/media/index.m3u8

任何链接都不行 我也卸载重装过

**Comment by youwen21** [comment]
@cy920820   你这链接是 vod 视频， 不是 IPTV 。

**Comment by cy920820** [comment]
> @cy920820 你这链接是 vod 视频， 不是 IPTV 。

我没用 IPTV，只是发现了 IPTV 管理页面白屏

我是想下载 m3u8 视频，之前还能用，现在点击下载都是 500

**Comment by youwen21** [comment]
@cy920820   我试下了，视频可播放、可下载。   你过版本升级吗？ 如果是多版本， 清理下原m3u8Data 文件夹

**Comment by youwen21** [comment]
1， 重启软件
2， 重启电脑
3， 清理 ～/ m3u8Data 文件夹

以上步骤可以逐步尝试。

**Comment by cy920820** [comment]
> 1， 重启软件 2， 重启电脑 3， 清理 ～/ m3u8Data 文件夹
> 
> 以上步骤可以逐步尝试。

大概率搞不定了   macOS 14.5 (23F79)

**Comment by youwen21** [comment]
@cy920820  下一版 专门指定下 arm arch 发到 QQ 群里。

**Comment by youwen21** [comment]
@cy920820   谢谢你的反馈， 问题已定位， 下一版本修复。  
因无IPTV数据导致， 导入 IPTV 后， 会转正常。

**Comment by cy920820** [comment]
> mac 端任何有效的 m3u8 链接，点击下载都会弹出这样的提示

新版本可以下载了，点赞

**Comment by cy920820** [comment]
新版本 导出mp4 功能直接软件闪退

**Comment by youwen21** [comment]
> 新版本 导出mp4 功能直接软件闪退

我本机测试正常。    方便的话发视频地址，看下视频什么情况。
软件导出mp4失败时，可使用 ffmpeg 导出。

**Comment by cy920820** [comment]
> > 新版本 导出mp4 功能直接软件闪退
> 
> 我本机测试正常。 方便的话发视频地址，看下视频什么情况。 软件导出mp4失败时，可使用 ffmpeg 导出。

我用 ffmpeg 导出了

**Comment by cy920820** [comment]
但是还有个问题， 视频可以在线播放，但是下载会报错

链接：https://c-vod-hw-k.xiaoeknow.com/asset/65326e36e1fc0657005e1f052b565ffb/8adc0a49e0b8101a0f6d7cd8f20d745c.m3u8?sign=6ef10252dfcef714c66561683b9ce56c&t=667a191e&us=ZyeeJktELL
