### ISSUE TITLE
支持特殊的m3u8格式吗？内部非常规的ts片段，而是一些mp4切片

### ISSUE THREAD

**Issue by Subdue0** [youwen21/flybird-downloader#4]
如题

**Comment by youwen21** [comment]
> 如题

发m3u8链接， 我看下是否能支持。

**Comment by Subdue0** [comment]
> > 如题
> 
> 发m3u8链接， 我看下是否能支持。

---链接失效， 隐藏---

**Comment by youwen21** [comment]
@Subdue0  感谢反馈， 后面不超过3个版本 支持。

**Comment by Subdue0** [comment]
> @Subdue0 感谢反馈， 后面不超过3个版本 支持。

还有aes 128加密的M3U8，有没有打算考虑支持？

**Comment by youwen21** [comment]
@Subdue0   加密解密目前支持aes 128，  碰到其他加密解密案例， 请提供一下链接。  如 eas 256 等

**Comment by Subdue0** [comment]
> @Subdue0 碰到有实际使用这个加密方式的就支持， 没碰到就搁置。 如果有使用aes 128案例， 请提供一下链接。

网络上，很多aes 128加密的M3U8，有专门的测试视频的

**Comment by youwen21** [comment]
@Subdue0   刚才检查了一下，  目前是支持AES128解密。    在”高级设置“ -> 解密保存。

也可以不勾选， 加密视频 也可以下载，播放。    无任何影响。    

如果 碰到解密失败情况 就删除视频重新下载， 不勾选 解密保存。    

个人使用，直接下载，不用管视频是否加密， 软件会自动处理。

**Comment by Subdue0** [comment]
> @Subdue0 刚才检查了一下， 目前是支持AES128解密。 在”高级设置“ -> 解密保存，

支持就好，赞

**Comment by Subdue0** [comment]
有dash格式的视频流，是不是不支持的

**Comment by youwen21** [comment]
dash格式 ，表达方式太多， 目前适配了一部分， 所以没上线。  
将来会支持dash 点播，直播不带加密的情况。   
有加密情况L3级的会慢慢支持。
L1,L2加密等级无法支持。

**Comment by Subdue0** [comment]
> dash格式 ，表达方式太多， 目前适配了一部分， 所以没上线。 将来会支持dash 点播，直播不带加密的情况。 有加密情况L3级的会慢慢支持。 L1,L2加密等级无法支持。

能支持L3就够用了

**Comment by youwen21** [comment]
@Subdue0   v3.2.4版本支持lowLatency 类型

**Comment by Subdue0** [comment]
> @Subdue0 v3.2.4版本支持lowLatency 类型

提示要激活才能用

**Comment by Subdue0** [comment]
![image](https://github.com/user-attachments/assets/8e2144a9-776b-4f81-a86f-7af53932b314)

**Comment by youwen21** [comment]
@Subdue0   免费申请个验证码 激活就可以了。

m3u8地址发和网站 发一下， 在qq群发
